import { app } from "@/app"

import swaggerAutogen from 'swagger-autogen'


const doc = {
    openapi: "3.0.3",
    info: {
        version: "1.0.0",
        title: "Subscription Tracker API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Auth",
            "description": "Authentication endpoints"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "api_key",
            in: "header"
        },
    },
    definitions: {
        
    }
}

const outputFile = './src/docs/swagger-output.json'
const endpointsFiles = ['./src/routes/auth.routes.ts']

swaggerAutogen(outputFile, endpointsFiles, doc)